# Generated by Django 4.0.5 on 2022-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_actionobjective_actionplan_actiontype_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
